"""
Configuration defaults for the wrestling league formulas.

This module exposes mutable live settings used by the application.
Pristine defaults are stored in src.settings_defaults.
"""

from copy import deepcopy

from src.settings_defaults import (
    LEVEL_EVALUATION_SETTINGS_DEFAULTS,
    MATCHMAKING_SETTINGS_DEFAULTS,
    RATINGS_SETTINGS_DEFAULTS,
    SCORING_SETTINGS_DEFAULTS,
    TEAM_RANKING_SETTINGS_DEFAULTS,
    TOKEN_SETTINGS_DEFAULTS,
    ATHLETE_RANKING_SETTINGS_DEFAULTS,
)

SCORING_SETTINGS = deepcopy(SCORING_SETTINGS_DEFAULTS)
MATCHMAKING_SETTINGS = deepcopy(MATCHMAKING_SETTINGS_DEFAULTS)
RATINGS_SETTINGS = deepcopy(RATINGS_SETTINGS_DEFAULTS)
TEAM_RANKING_SETTINGS = deepcopy(TEAM_RANKING_SETTINGS_DEFAULTS)
TOKEN_SETTINGS = deepcopy(TOKEN_SETTINGS_DEFAULTS)
LEVEL_EVALUATION_SETTINGS = deepcopy(LEVEL_EVALUATION_SETTINGS_DEFAULTS)
ATHLETE_RANKING_SETTINGS = deepcopy(ATHLETE_RANKING_SETTINGS_DEFAULTS)